[versions]
agp = "8.13.0"
kotlin = "2.0.21"
smartscanCore = "1.1.1"

[libraries]

smartscan-core = { module = "com.github.dev-diaries41.smartscan-sdk:smartscan-core", version.ref = "smartscanCore" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

